### ISSUE TITLE
Default zoom level is 'full out', consider defaulting to a closer zoom level

### ISSUE THREAD

**Issue by dylanbuli** [geeksville/Gaggle#15]
When I go to the map screen on boot it shows like 3 copies of the planet.  Not sure if thats a useful zoom level (at least for my current soaring skill level ;-)  ).

Once zoomed, gaggle does seem to keep the level set correctly until it is killed.

**Comment by geeksville** [comment]
Thanks.  Fixed in my latest checkin.
