### ISSUE TITLE
Enhancement: Waypoint help page, change to point to world turnpoint exchange, fix dead wpt

### ISSUE THREAD

**Issue by dylanbuli** [geeksville/Gaggle#16]
The British Solvania open that is on the waypoints help page (when there are no waypoints) is broken.

Consider replacing it with the World turnpoint exchange. Maybe this text:
By visiting a waypoint (.wpt) file on the web and choosing the "Open with Gaggle" choice in the browser.

Many waypoint files can be found in the Worldwide Soaring Turnpoint Exchange (http://soaringweb.org/TP). The CompeGPS and OziExplorer formats are known to work. For example, Boulder, CO USA (http://soaringweb.org/TP/Boulder_100/b540_ozi.wpt)

**Comment by geeksville** [comment]
Thanks fixed in next release.
