### ISSUE TITLE
Change .classpath to have relative link osmdroid jar 

### ISSUE THREAD

**Issue by dylanbuli** [geeksville/Gaggle#17]
Suggest changing .classpath file:
    <classpathentry kind="lib" path="/home/kevinh/development/Gaggle/libs/osmdroid-android-1.07.jar" sourcepath="/osmdroid-android"/>
to 
    <classpathentry kind="lib" path="libs/osmdroid-android-1.07.jar" sourcepath="/osmdroid-android"/>

**Comment by geeksville** [comment]
Thanks - will be fixed with my next git push (a few hrs)
