### ISSUE TITLE
Gaggle image tiles appear in G2 photo album

### ISSUE THREAD

**Issue by O1O1O1O** [geeksville/Gaggle#23]
After I loaded up Gaggle on my G2 and checked out some maps I later discovered that the photo album app included pages and pages of the G2 map tiles.  Is there any way to hide Gaggles storage of tiles from the builtin apps?

**Comment by geeksville** [comment]
Thank you for the report.  I'll fix this bug right now.  The update should go to the market within the hour.

**Comment by O1O1O1O** [comment]
Thanks Kevin - I was going to show you on Saturday but didn't have time!  After erasing the osmdroid folder from the SD (I had to mount the card on my laptop to do that) and loading the gallery app it took a little while but eventually noticed they were gone.  I reloaded Gaggle, browsed some maps and the titles did not return.  Case close!
