### ISSUE TITLE
FlyNet support

### ISSUE THREAD

**Issue by relet** [geeksville/Gaggle#66]
I would like to see support for the flynet bluetooth device. 
developer documentation: https://asinstrument.ch/pages/download

If I manage to compile the project, I might handle this issue myself, but any support is welcome. :)

**Comment by dkm** [comment]
On 06/08/2012 02:03 PM, Thomas Hirsch wrote:

> I would like to see support for the flynet bluetooth device.
> developer documentation: https://asinstrument.ch/pages/download
> 
> If I manage to compile the project, I might handle this issue myself, but any support is welcome. :)

I'm working on a very similar project, so we may be able to work 
together for some details.

**Comment by relet** [comment]
I got a working module, and will send a pull notification when it worksforme in flight. 

https://github.com/relet/Gaggle/blob/master/src/com/geeksville/location/FlynetBarometerClient.java

**Comment by relet** [comment]
Basic support is available and in trunk, so I'm closing this ticket.
