### ISSUE TITLE
Enhancement - adjustment to altitude

### ISSUE THREAD

**Issue by chanoch** [geeksville/Gaggle#83]
From Edward Cunliffe

How easy or difficult would it be to build in an altitude correction?

WGS84 Spheroid and all that ... Gaggle (and memory Map, and PPGGPS etc) all report about 200ft higher than I really am here in the North East UK, ideally we'd use WGS84 but a simple alti correction factor would be good?

Ed

**Comment by dkm** [comment]
fixed in master-next
